sudo: required

services:
  - docker

language: generic

# https://github.com/travis-ci/travis-ci/issues/5358
cache:
  directories:
  - docker_images
before_install:
  - docker load -i docker_images/images.tar || true
before_cache:
  - docker save -o docker_images/images.tar rockerverse

install:
  - docker build --tag rockerverse .

build:
  - docker run -i -v $(pwd):/rockerverse rockerverse Rscript -e 'setwd("/rockerverse"); rmarkdown::render("manuscript.Rmd")'

# only works for one branch, because of reset
after_success:
  - mkdir -p site
  - cp RJwrapper.pdf site/$TRAVIS_BRANCH.pdf
  - cd site
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git remote add upstream "https://${GH_TOKEN}@${GH_REF}"
  - git fetch upstream
  - git reset upstream/gh-pages
  - git add -A .
  - rev=$(git rev-parse --short HEAD)
  - git commit -m "Rebuild at ${rev}"
  - git push -q upstream HEAD:gh-pages
